#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# The build scripts source .env, so every path captured here lands there.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

banner "dot-tower — Android bringup setup"

# ──────────────────────────────────────────────────────────────────────────
stage "Homebrew"
say "Everything below installs through Homebrew."
if command -v brew >/dev/null 2>&1; then
  note "found $(brew --version | head -1)"
else
  warn "Homebrew is not installed."
  open_url "https://brew.sh"
  step "Follow the one-line install command on that page, then re-run this wizard."
  exit 1
fi
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "JDK 17"
say "Android Gradle Plugin 8.13 needs a JDK. 17 is the version this project"
say "compiles against (see android/app/build.gradle compileOptions)."
if /usr/libexec/java_home -v 17 >/dev/null 2>&1; then
  note "JDK 17 already present"
else
  say "Installing Temurin 17. macOS will ask for your password — casks install"
  say "into /Library, which needs admin rights."
  if confirm "Run 'brew install --cask temurin@17' now?"; then
    brew install --cask temurin@17
  else
    SKIPPED+=("JDK 17 (brew install --cask temurin@17)")
    warn "skipped — Gradle will not run without it"
  fi
fi
if JAVA_HOME_PATH=$(/usr/libexec/java_home -v 17 2>/dev/null); then
  write_env JAVA_HOME "$JAVA_HOME_PATH"
  note "java: $("$JAVA_HOME_PATH/bin/java" -version 2>&1 | head -1)"
fi
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "Android command-line tools"
say "This gives us sdkmanager and adb without installing Android Studio."
if command -v sdkmanager >/dev/null 2>&1 || [[ -d "$HOME/Library/Android/sdk/cmdline-tools" ]]; then
  note "command-line tools already present"
else
  if confirm "Run 'brew install --cask android-commandlinetools' now?"; then
    brew install --cask android-commandlinetools
  else
    SKIPPED+=("android-commandlinetools")
  fi
fi

# Homebrew's cask puts the SDK under its own prefix; fall back to the
# conventional location if someone already had a manual install.
BREW_SDK="$(brew --prefix 2>/dev/null)/share/android-commandlinetools"
if [[ -d "$BREW_SDK" ]]; then
  ANDROID_SDK="$BREW_SDK"
elif [[ -d "$HOME/Library/Android/sdk" ]]; then
  ANDROID_SDK="$HOME/Library/Android/sdk"
else
  warn "could not locate an Android SDK directory"
  ask ANDROID_HOME "Enter the full path to your Android SDK:"
  ANDROID_SDK="$ANDROID_HOME"
fi
write_env ANDROID_HOME "$ANDROID_SDK"
note "SDK root: $ANDROID_SDK"
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "Accept the SDK licences"
say "Google requires a human to accept these. An agent must not accept them"
say "on your behalf, so this stage is yours."
say ""
step "A licence text will scroll past. Type 'y' at each prompt to accept."
pause "Press Enter to start accepting licences"
SDKMANAGER="$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager"
[[ -x "$SDKMANAGER" ]] || SDKMANAGER="$(command -v sdkmanager || true)"
if [[ -n "$SDKMANAGER" && -x "$SDKMANAGER" ]]; then
  JAVA_HOME="${JAVA_HOME_PATH:-${JAVA_HOME:-}}" "$SDKMANAGER" --sdk_root="$ANDROID_SDK" --licenses || \
    warn "licence step exited non-zero — re-run this wizard if packages fail below"
else
  SKIPPED+=("SDK licences (run: sdkmanager --licenses)")
  warn "sdkmanager not found — cannot accept licences"
fi
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "SDK packages — API 36, build-tools, platform-tools, NDK"
say "API 36 because Google Play requires it for updates from 2026-08-31."
say "The NDK is what compiles the Rust cdylib and android-activity's C++ glue."
if [[ -n "${SDKMANAGER:-}" && -x "$SDKMANAGER" ]]; then
  # Pick the newest stable NDK the SDK offers, rather than pinning a build
  # number that may not exist by the time this runs.
  NDK_PKG=$(JAVA_HOME="${JAVA_HOME_PATH:-${JAVA_HOME:-}}" "$SDKMANAGER" --sdk_root="$ANDROID_SDK" --list 2>/dev/null \
    | awk -F'|' '/^[[:space:]]*ndk;[0-9]+\.[0-9]+\.[0-9]+[[:space:]]*\|/ {gsub(/ /,"",$1); print $1}' \
    | sort -t';' -k2 -V | tail -1)
  [[ -n "$NDK_PKG" ]] || NDK_PKG="ndk;27.2.12479018"
  say "Installing: platform-tools, platforms;android-36, build-tools;36.0.0, $NDK_PKG"
  if confirm "Install these now? (a few hundred MB)"; then
    JAVA_HOME="${JAVA_HOME_PATH:-${JAVA_HOME:-}}" "$SDKMANAGER" --sdk_root="$ANDROID_SDK" \
      "platform-tools" "platforms;android-36" "build-tools;36.0.0" "$NDK_PKG"
  else
    SKIPPED+=("SDK packages")
  fi
  NDK_VERSION="${NDK_PKG#ndk;}"
  if [[ -d "$ANDROID_SDK/ndk/$NDK_VERSION" ]]; then
    write_env ANDROID_NDK_HOME "$ANDROID_SDK/ndk/$NDK_VERSION"
    # Gradle resolves the games-activity prefab against this exact NDK.
    tmp=$(mktemp)
    grep -v '^ndkVersion=' android/gradle.properties > "$tmp" || true
    printf 'ndkVersion=%s\n' "$NDK_VERSION" >> "$tmp"
    mv "$tmp" android/gradle.properties
    printf '  %s✓ wrote%s ndkVersion=%s → android/gradle.properties\n' "$GREEN" "$RESET" "$NDK_VERSION"
  else
    SKIPPED+=("NDK (expected at $ANDROID_SDK/ndk/$NDK_VERSION)")
    warn "NDK directory not found after install"
  fi
else
  SKIPPED+=("SDK packages — sdkmanager missing")
fi
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "Gradle wrapper"
say "Pinning the wrapper keeps this build reproducible across machines."
if [[ -x android/gradlew ]]; then
  note "android/gradlew already present"
else
  command -v gradle >/dev/null 2>&1 || {
    say "Installing Gradle (used once, to generate the wrapper)."
    confirm "Run 'brew install gradle' now?" && brew install gradle || SKIPPED+=("gradle")
  }
  if command -v gradle >/dev/null 2>&1; then
    ( cd android && JAVA_HOME="${JAVA_HOME_PATH:-${JAVA_HOME:-}}" gradle wrapper --gradle-version 8.14.3 ) \
      && note "wrapper generated" \
      || SKIPPED+=("gradle wrapper (cd android && gradle wrapper --gradle-version 8.14.3)")
  fi
fi
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "Phone — enable USB debugging"
say "This part only you can do; it needs the physical handset."
say ""
step "Settings → About phone → tap 'Build number' seven times."
step "You'll see 'You are now a developer'. Enter your PIN if asked."
step "Go back → System → Developer options (on Samsung: Settings → Developer options)."
step "Turn ON 'USB debugging'."
step "While you're there, turn ON 'Stay awake' — it saves a lot of re-unlocking."
say ""
note "Probe C reads the display cutout, so if this handset has a notch or"
note "punch-hole, that is the interesting device to use."
pause "Press Enter once USB debugging is on"

# ──────────────────────────────────────────────────────────────────────────
stage "Phone — authorise this Mac"
ADB="$ANDROID_SDK/platform-tools/adb"
[[ -x "$ADB" ]] || ADB="$(command -v adb || true)"
step "Plug the phone into this Mac with a USB data cable."
note "Charge-only cables are the single most common cause of an empty device"
note "list. If nothing shows up, try a different cable first."
step "On the phone, accept 'Allow USB debugging?' — tick 'Always allow'."
pause "Press Enter once it's plugged in and authorised"

if [[ -n "$ADB" && -x "$ADB" ]]; then
  "$ADB" start-server >/dev/null 2>&1 || true
  say ""
  "$ADB" devices
  DEVICE_COUNT=$("$ADB" devices | awk 'NR>1 && $2=="device"' | wc -l | tr -d ' ')
  if [[ "$DEVICE_COUNT" == "0" ]]; then
    warn "no authorised device yet."
    note "'unauthorized' means the on-phone prompt hasn't been accepted."
    note "nothing listed at all means the cable or port is not carrying data."
    SKIPPED+=("device authorisation — re-run: $ADB devices")
  else
    MODEL=$("$ADB" shell getprop ro.product.model 2>/dev/null | tr -d '\r')
    RELEASE=$("$ADB" shell getprop ro.build.version.release 2>/dev/null | tr -d '\r')
    SDKV=$("$ADB" shell getprop ro.build.version.sdk 2>/dev/null | tr -d '\r')
    printf '  %s✓ connected:%s %s — Android %s (API %s)\n' "$GREEN" "$RESET" "$MODEL" "$RELEASE" "$SDKV"
    # Ticket 04 asks for the tested device and OS version on resolution.
    write_env BRINGUP_DEVICE "$MODEL (Android $RELEASE, API $SDKV)"
  fi
else
  SKIPPED+=("adb not found")
fi
pause "Press Enter to continue"

# ──────────────────────────────────────────────────────────────────────────
stage "Build and run"
say "Everything from here is automated."
say ""
say "  ./scripts/android-run.sh"
say ""
say "That builds the Rust cdylib, packages the APK, installs it, launches it,"
say "and tails the probe log."
say ""
note "On screen you should see a yellow square that follows your finger, four"
note "buttons along the bottom, a red safe-area frame, and a HUD reading out"
note "probes A-E. What each probe is testing is documented at the top of"
note "src/lib.rs."
say ""
if confirm "Run it now?"; then
  ./scripts/android-run.sh || warn "build failed — the error above is the finding; record it on ticket 04"
fi

finish
